### ISSUE TITLE
Test-Most-0.37 suffers from the PaxHeader phenomenon

### ISSUE THREAD

**Issue by XSven** [Ovid/test--most#16]
Test::Most version 0.37 suffers from the PaxHeader phenomenon described here [New tar, paxheaders and installing from CPAN](https://huntingbears.nl/2015/02/17/new-tar-paxheaders-and-installing-from-cpan/). Im am running perl 5.14.2 on an AIX 7.2 host. Until now I wasn't able to overcome this problem. Are you willing to change the packaging?!

**Comment by XSven** [comment]
I have solved the problem changing the tar attribute of the cpan shell from AIX tar to gtar. Please feel free to close this issue, if you don't want to change/fix the packaging.

**Comment by DrHyde** [comment]
This also affects Solaris.

And users of `cpanm` *can't*, as far as I can see, tell it which `tar` to use.

**Comment by DrHyde** [comment]
Appears to have been fixed for Solaris in 0.38, presumably by using a different version of tar.

**Comment by Ovid** [comment]
@DrHyde Would you like comaint? I'm idiotically busy right now and haven't been taking care of my modules the way I should be.

**Comment by DrHyde** [comment]
Sure. And so that we don't end up with two repos with different code in, wanna either transfer the repo to me, or give me a commit bit so I can merge changes here?

**Comment by Ovid** [comment]
Thank you! I've added you on GitHub and PAUSE.
